
set -g base-index 1 
set -g pane-base-index 1
set -g renumber-windows on
set -g focus-events on
set -g aggressive-resize on
set -s escape-time 10

set -g default-command "${SHELL}"
set -g default-terminal "tmux-256color"
set -as terminal-features ",xterm-256color:RGB"

set -g status-style "bg=default"
set -g status-left ""
set -g status-right "#[fg=white,bold][#[fg=green]#{USER}#[fg=blue]@#H #[fg=yellow]#S#[fg=white]]"
set -g status-right-length 64
set -g window-status-style "fg=white,bold"
set -g window-status-current-style "fg=green,bold"
set -g pane-border-style "fg=white,bold"
set -g pane-active-border-style "fg=green,bold"

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

set -g status-keys vi
setw -g mode-keys vi
